# Generated by Django 5.2.1 on 2025-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ephios_youthwarden", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minorparticipationrequest",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Ausstehend"), (1, "Angenommen"), (2, "Abgelehnt")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
