# Generated by Django 5.2.3 on 2025-07-11 11:10

import django.db.models.deletion
from django.db import migrations, models

from ephios_youthwarden.consequences import MinorParticipationRequestConsequenceHandler


def set_minor_request_consequence(apps, schema_editor):
    MinorParticipationRequest = apps.get_model("ephios_youthwarden", "minorparticipationrequest")
    Consequence = apps.get_model("core", "consequence")
    for r in MinorParticipationRequest.objects.all():
        # we need to fill the link to consequences, so we don't unintentionally
        # delete consequences created before the addition of the deletion mechanism
         for c in Consequence.objects.filter(
                slug=MinorParticipationRequestConsequenceHandler.slug,
                user=r.user,
            ):
             if c.data.get("shift") == r.shift_id:
                 r.consequence = c
                 r.save()
                 break


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_eventtype_default_description"),
        ("ephios_youthwarden", "0002_alter_minorparticipationrequest_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="minorparticipationrequest",
            name="consequence",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minor_request",
                to="core.consequence",
            ),
        ),
        migrations.RunPython(set_minor_request_consequence),
    ]
